### ISSUE TITLE
Use gitoxyde or libgit2 bindings to avoid relying on bash and git cli

### ISSUE THREAD

**Issue by florentinl** [florentinl/giga#54]

**Comment by GerfautGE** [comment]
I implemented the git diff compute using git2 in the commit 3c70adb . but there is still some issues with the line cout.
maybe you can help me fix that...

**Comment by GerfautGE** [comment]
I fix line count  in commit 408794b518bd4e923c0a4679e939bf834c76cb59 but now delete patches are not displayed
